export const RouteName = {
  HOME: "/",
  COLLECTIONS: "/collections",
  OUR_STORY: "/our-story",
  ARTISANS: "/artisans",
  PRODUCT_DETAIL: "/product/:id",
  ORGANIC_LUXURY: "/organic-luxury",
  CUSTOM_ORDER: "/custom-order",
  MASTERCLASS: "/masterclass",
  LEARNING_HUB: "/learning-hub",
  CONTACT: "/contact",
  CHECKOUT: "/checkout",
  AUTH: "/auth",
  PROFILE: "/profile",
  MY_ORDERS: "/my-orders",
  ORDERS: "/my-orders",
  NOT_FOUND: "*",
};
